/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


#include <wchar.h>
#include "Parser.h"
#include "Scanner.h"


namespace Four20 {


void Parser::SynErr(int n) {
	if (errDist >= minErrDist) errors->SynErr(la->line, la->col, n);
	errDist = 0;
}

void Parser::SemErr(const wchar_t* msg) {
	if (errDist >= minErrDist) errors->Error(t->line, t->col, msg);
	errDist = 0;
}

void Parser::Get() {
	for (;;) {
		t = la;
		la = scanner->Scan();
		if (la->kind <= maxT) { ++errDist; break; }

		if (dummyToken != t) {
			dummyToken->kind = t->kind;
			dummyToken->pos = t->pos;
			dummyToken->col = t->col;
			dummyToken->line = t->line;
			dummyToken->next = NULL;
			coco_string_delete(dummyToken->val);
			dummyToken->val = coco_string_create(t->val);
			t = dummyToken;
		}
		la = t;
	}
}

void Parser::Expect(int n) {
	if (la->kind==n) Get(); else { SynErr(n); }
}

void Parser::ExpectWeak(int n, int follow) {
	if (la->kind == n) Get();
	else {
		SynErr(n);
		while (!StartOf(follow)) Get();
	}
}

bool Parser::WeakSeparator(int n, int syFol, int repFol) {
	if (la->kind == n) {Get(); return true;}
	else if (StartOf(repFol)) {return false;}
	else {
		SynErr(n);
		while (!(StartOf(syFol) || StartOf(repFol) || StartOf(0))) {
			Get();
		}
		return StartOf(syFol);
	}
}

void Parser::variableProd(wchar_t* &name) {
		Expect(_variable);
		name = coco_string_create(t->val); 
}

void Parser::factor() {
		wchar_t* name; 
		if (la->kind == _character) {
			Get();
		} else if (la->kind == _variable) {
			Get();
		} else if (la->kind == _string) {
			Get();
		} else if (la->kind == _number) {
			Get();
		} else if (la->kind == _idenToken) {
			identifier(name);
		} else SynErr(31);
}

void Parser::identifier(wchar_t* &name) {
		Expect(_idenToken);
		name = coco_string_create(t->val); 
}

void Parser::additationOperator(Operator &op) {
		op = Operator::ADD; 
		if (la->kind == 6 /* "+" */) {
			Get();
		} else if (la->kind == 7 /* "-" */) {
			Get();
			op = Operator::SUB; 
		} else SynErr(32);
}

void Parser::multiplyOperator(Operator &op) {
		op = Operator::MUL; 
		if (la->kind == 8 /* "*" */) {
			Get();
		} else if (la->kind == 9 /* "/" */) {
			Get();
			op = Operator::DIV; 
		} else SynErr(33);
}

void Parser::relationalOperator(Operator &op) {
		op = Operator::EQU; 
		if (la->kind == 10 /* "==" */) {
			Get();
		} else if (la->kind == 11 /* "!=" */) {
			Get();
			op = Operator::NEQ; 
		} else if (la->kind == 12 /* ">" */) {
			Get();
			op = Operator::LSS; 
		} else if (la->kind == 13 /* "<" */) {
			Get();
			op = Operator::GTR; 
		} else SynErr(34);
}

void Parser::simpleExpression() {
		Operator op; 
		if (la->kind == 6 /* "+" */ || la->kind == 7 /* "-" */) {
			additationOperator(op);
			factor();
		} else if (la->kind == 8 /* "*" */ || la->kind == 9 /* "/" */) {
			multiplyOperator(op);
			factor();
		} else if (StartOf(1)) {
			relationalOperator(op);
			factor();
		} else SynErr(35);
}

void Parser::expression() {
		factor();
		while (StartOf(2)) {
			simpleExpression();
		}
}

void Parser::ifStatement() {
		Expect(14 /* "jeigu" */);
		expression();
		statement();
		if (la->kind == 15 /* "kitaip" */) {
			Get();
			statement();
		}
}

void Parser::statement() {
		if (la->kind == 18 /* "char" */ || la->kind == 19 /* "string" */ || la->kind == 20 /* "int" */) {
			declaration();
		} else if (la->kind == _variable) {
			Get();
			Expect(16 /* "=" */);
			expression();
			Expect(17 /* ";" */);
		} else if (la->kind == 14 /* "jeigu" */) {
			ifStatement();
		} else if (la->kind == 26 /* "nuo" */) {
			forStatement();
		} else if (la->kind == _idenToken) {
			procedureStatement();
		} else SynErr(36);
}

void Parser::declaration() {
		wchar_t* name; Type type; 
		typeSpecifier(type);
		variableProd(name);
		if (la->kind == 16 /* "=" */) {
			Get();
			expression();
		}
		curProc->add(new Var(name, type)); 
		Expect(17 /* ";" */);
}

void Parser::forStatement() {
		Expect(26 /* "nuo" */);
		Expect(_variable);
		if (la->kind == 16 /* "=" */) {
			Get();
			expression();
		}
		Expect(27 /* "iki" */);
		expression();
		Expect(28 /* "daryti" */);
		statement();
		statement();
}

void Parser::procedureStatement() {
		wchar_t* name; 
		identifier(name);
		Expect(22 /* "(" */);
		while (StartOf(3)) {
			factor();
		}
		Expect(23 /* ")" */);
		Expect(17 /* ";" */);
}

void Parser::Four20() {
		curProc = new Procedure(L"Main", Type::UNDEF, NULL, this); 
		while (la->kind == 29 /* "#define" */) {
			define();
		}
		while (la->kind == 18 /* "char" */ || la->kind == 19 /* "string" */ || la->kind == 20 /* "int" */) {
			declaration();
		}
		while (la->kind == 21 /* "procedura" */) {
			procedureDeclaration();
		}
}

void Parser::define() {
		wchar_t* name; 
		Expect(29 /* "#define" */);
		identifier(name);
		factor();
}

void Parser::procedureDeclaration() {
		wchar_t* name; wchar_t* varName; Type type;
		Expect(21 /* "procedura" */);
		identifier(name);
		Procedure* oldProc = curProc;
		     curProc = new Procedure(name, Type::UNDEF, oldProc, this);
		     oldProc->add(curProc); 
		Expect(22 /* "(" */);
		while (la->kind == 18 /* "char" */ || la->kind == 19 /* "string" */ || la->kind == 20 /* "int" */) {
			typeSpecifier(type);
			variableProd(varName);
		}
		Expect(23 /* ")" */);
		Expect(24 /* "{" */);
		while (StartOf(4)) {
			statement();
		}
		Expect(25 /* "}" */);
		curProc = oldProc; 
}

void Parser::typeSpecifier(Type &type) {
		if (la->kind == 18 /* "char" */) {
			type = Type::CHAR; 
			Get();
		} else if (la->kind == 19 /* "string" */) {
			Get();
			type = Type::STRING; 
		} else if (la->kind == 20 /* "int" */) {
			Get();
			type = Type::INT; 
		} else SynErr(37);
}




// If the user declared a method Init and a mehtod Destroy they should
// be called in the contructur and the destructor respctively.
//
// The following templates are used to recognize if the user declared
// the methods Init and Destroy.

template<typename T>
struct ParserInitExistsRecognizer {
	template<typename U, void (U::*)() = &U::Init>
	struct ExistsIfInitIsDefinedMarker{};

	struct InitIsMissingType {
		char dummy1;
	};
	
	struct InitExistsType {
		char dummy1; char dummy2;
	};

	// exists always
	template<typename U>
	static InitIsMissingType is_here(...);

	// exist only if ExistsIfInitIsDefinedMarker is defined
	template<typename U>
	static InitExistsType is_here(ExistsIfInitIsDefinedMarker<U>*);

	enum { InitExists = (sizeof(is_here<T>(NULL)) == sizeof(InitExistsType)) };
};

template<typename T>
struct ParserDestroyExistsRecognizer {
	template<typename U, void (U::*)() = &U::Destroy>
	struct ExistsIfDestroyIsDefinedMarker{};

	struct DestroyIsMissingType {
		char dummy1;
	};
	
	struct DestroyExistsType {
		char dummy1; char dummy2;
	};

	// exists always
	template<typename U>
	static DestroyIsMissingType is_here(...);

	// exist only if ExistsIfDestroyIsDefinedMarker is defined
	template<typename U>
	static DestroyExistsType is_here(ExistsIfDestroyIsDefinedMarker<U>*);

	enum { DestroyExists = (sizeof(is_here<T>(NULL)) == sizeof(DestroyExistsType)) };
};

// The folloing templates are used to call the Init and Destroy methods if they exist.

// Generic case of the ParserInitCaller, gets used if the Init method is missing
template<typename T, bool = ParserInitExistsRecognizer<T>::InitExists>
struct ParserInitCaller {
	static void CallInit(T *t) {
		// nothing to do
	}
};

// True case of the ParserInitCaller, gets used if the Init method exists
template<typename T>
struct ParserInitCaller<T, true> {
	static void CallInit(T *t) {
		t->Init();
	}
};

// Generic case of the ParserDestroyCaller, gets used if the Destroy method is missing
template<typename T, bool = ParserDestroyExistsRecognizer<T>::DestroyExists>
struct ParserDestroyCaller {
	static void CallDestroy(T *t) {
		// nothing to do
	}
};

// True case of the ParserDestroyCaller, gets used if the Destroy method exists
template<typename T>
struct ParserDestroyCaller<T, true> {
	static void CallDestroy(T *t) {
		t->Destroy();
	}
};

void Parser::Parse() {
	t = NULL;
	la = dummyToken = new Token();
	la->val = coco_string_create(L"Dummy Token");
	Get();
	Four20();
	Expect(0);
}

Parser::Parser(Scanner *scanner) {
	maxT = 30;

	ParserInitCaller<Parser>::CallInit(this);
	dummyToken = NULL;
	t = la = NULL;
	minErrDist = 2;
	errDist = minErrDist;
	this->scanner = scanner;
	errors = new Errors();
}

bool Parser::StartOf(int s) {
	const bool T = true;
	const bool x = false;

	static bool set[5][32] = {
		{T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x},
		{x,x,x,x, x,x,x,x, x,x,T,T, T,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x},
		{x,x,x,x, x,x,T,T, T,T,T,T, T,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x},
		{x,T,T,T, T,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x},
		{x,T,x,x, T,x,x,x, x,x,x,x, x,x,T,x, x,x,T,T, T,x,x,x, x,x,T,x, x,x,x,x}
	};



	return set[s][la->kind];
}

Parser::~Parser() {
	ParserDestroyCaller<Parser>::CallDestroy(this);
	delete errors;
	delete dummyToken;
}

Errors::Errors() {
	count = 0;
}

void Errors::SynErr(int line, int col, int n) {
	wchar_t* s;
	switch (n) {
			case 0: s = coco_string_create(L"EOF expected"); break;
			case 1: s = coco_string_create(L"idenToken expected"); break;
			case 2: s = coco_string_create(L"character expected"); break;
			case 3: s = coco_string_create(L"number expected"); break;
			case 4: s = coco_string_create(L"variable expected"); break;
			case 5: s = coco_string_create(L"string expected"); break;
			case 6: s = coco_string_create(L"\"+\" expected"); break;
			case 7: s = coco_string_create(L"\"-\" expected"); break;
			case 8: s = coco_string_create(L"\"*\" expected"); break;
			case 9: s = coco_string_create(L"\"/\" expected"); break;
			case 10: s = coco_string_create(L"\"==\" expected"); break;
			case 11: s = coco_string_create(L"\"!=\" expected"); break;
			case 12: s = coco_string_create(L"\">\" expected"); break;
			case 13: s = coco_string_create(L"\"<\" expected"); break;
			case 14: s = coco_string_create(L"\"jeigu\" expected"); break;
			case 15: s = coco_string_create(L"\"kitaip\" expected"); break;
			case 16: s = coco_string_create(L"\"=\" expected"); break;
			case 17: s = coco_string_create(L"\";\" expected"); break;
			case 18: s = coco_string_create(L"\"char\" expected"); break;
			case 19: s = coco_string_create(L"\"string\" expected"); break;
			case 20: s = coco_string_create(L"\"int\" expected"); break;
			case 21: s = coco_string_create(L"\"procedura\" expected"); break;
			case 22: s = coco_string_create(L"\"(\" expected"); break;
			case 23: s = coco_string_create(L"\")\" expected"); break;
			case 24: s = coco_string_create(L"\"{\" expected"); break;
			case 25: s = coco_string_create(L"\"}\" expected"); break;
			case 26: s = coco_string_create(L"\"nuo\" expected"); break;
			case 27: s = coco_string_create(L"\"iki\" expected"); break;
			case 28: s = coco_string_create(L"\"daryti\" expected"); break;
			case 29: s = coco_string_create(L"\"#define\" expected"); break;
			case 30: s = coco_string_create(L"??? expected"); break;
			case 31: s = coco_string_create(L"invalid factor"); break;
			case 32: s = coco_string_create(L"invalid additationOperator"); break;
			case 33: s = coco_string_create(L"invalid multiplyOperator"); break;
			case 34: s = coco_string_create(L"invalid relationalOperator"); break;
			case 35: s = coco_string_create(L"invalid simpleExpression"); break;
			case 36: s = coco_string_create(L"invalid statement"); break;
			case 37: s = coco_string_create(L"invalid typeSpecifier"); break;

		default:
		{
			wchar_t format[20];
			coco_swprintf(format, 20, L"error %d", n);
			s = coco_string_create(format);
		}
		break;
	}
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
	coco_string_delete(s);
	count++;
}

void Errors::Error(int line, int col, const wchar_t *s) {
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
	count++;
}

void Errors::Warning(int line, int col, const wchar_t *s) {
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
}

void Errors::Warning(const wchar_t *s) {
	wprintf(L"%ls\n", s);
}

void Errors::Exception(const wchar_t* s) {
	wprintf(L"%ls", s); 
	exit(1);
}

} // namespace

